; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=open codecpack 
AppVerName=open codecpack 6.4.0.3
AppPublisher=ewfilters team
AppPublisherURL=https://github.com/emabiz/e-works-codecpack
AppSupportURL=https://github.com/emabiz/e-works-codecpack
AppUpdatesURL=https://github.com/emabiz/e-works-codecpack
DefaultDirName={userappdata}\e-works\opencodecpack
DefaultGroupName=e-works\opencodecpack
DisableProgramGroupPage=yes
OutputDir=.\
OutputBaseFilename=opencodecpack_setup
Compression=lzma
SolidCompression=yes
VersionInfoVersion=6.4.0.3
PrivilegesRequired=none
UsePreviousAppDir=yes

[Languages]
Name: "en"; MessagesFile: "compiler:Default.isl"; LicenseFile: "..\LICENSE"
Name: "fr"; MessagesFile: "compiler:Languages\French.isl"; LicenseFile: "..\LICENSE"
Name: "de"; MessagesFile: "compiler:Languages\German.isl"; LicenseFile: "..\LICENSE"
Name: "it"; MessagesFile: "compiler:Languages\Italian.isl"; LicenseFile: "..\LICENSE"
Name: "es"; MessagesFile: "compiler:Languages\Spanish.isl"; LicenseFile: "..\LICENSE"
Name: "ru"; MessagesFile: "compiler:Languages\Russian.isl"; LicenseFile: "..\LICENSE"

[Files]
;dll
Source: "..\Release\avcodec-53.dll"; DestDir: "{app}\dll"; Flags: ignoreversion
Source: "..\Release\avformat-53.dll"; DestDir: "{app}\dll"; Flags: ignoreversion
Source: "..\Release\avutil-51.dll"; DestDir: "{app}\dll"; Flags: ignoreversion
Source: "..\Release\swscale-2.dll"; DestDir: "{app}\dll"; Flags: ignoreversion
Source: "..\Release\ewh263.dll"; DestDir: "{app}\dll"; Flags: ignoreversion
Source: "..\Release\ewh264.dll"; DestDir: "{app}\dll"; Flags: ignoreversion
Source: "..\Release\ewxvid.dll"; DestDir: "{app}\dll"; Flags: ignoreversion
Source: "..\Release\libx264-136.dll"; DestDir: "{app}\dll"; Flags: ignoreversion
Source: "..\Release\libpthread-2.dll"; DestDir: "{app}\dll"; Flags: ignoreversion
Source: "..\Release\xvidcore.dll"; DestDir: "{app}\dll"; Flags: ignoreversion

;ewautore conf
Source: ".\conf\*.container"; DestDir: "{app}\conf"; Flags: recursesubdirs
Source: ".\conf\*.phone"; DestDir: "{app}\conf"; Flags: recursesubdirs
Source: ".\conf\*.params"; DestDir: "{app}\conf"; Flags: recursesubdirs
Source: ".\conf\*.profile"; DestDir: "{app}\conf"; Flags: recursesubdirs
Source: ".\conf\*.cbr"; DestDir: "{app}\conf"; Flags: recursesubdirs
Source: ".\conf\*.vbr"; DestDir: "{app}\conf"; Flags: recursesubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

;misc
Source: "..\LICENSE"; DestDir: "{app}"; DestName: "LICENSE.TXT"; Flags: ignoreversion

[Icons]
Name: "{group}\License"; Filename: "{app}\LICENSE.TXT"
Name: "{group}\{cm:UninstallProgram,opencodecpack}"; Filename: "{uninstallexe}"